PORTNAME=	libpipeline
DISTVERSION=	1.5.7
CATEGORIES=	devel
MASTER_SITES=	SAVANNAH/libpipeline

MAINTAINER=	zirias@FreeBSD.org
COMMENT=	Pipeline manipulation library for Linux
WWW=		https://libpipeline.nongnu.org/

LICENSE=	GPLv3
LICENSE_FILE=	${WRKSRC}/COPYING

USES=		libtool linuxsrc:base,man

GNU_CONFIGURE=	yes
INSTALL_TARGET=	install-strip

.include <bsd.port.mk>
