PORTNAME=	linuxsrc-devtools
PORTVERSION=	1
CATEGORIES=	devel

MAINTAINER=	zirias@FreeBSD.org
COMMENT=	Basic Linux development tools (C and C++)

RUN_DEPENDS=	linuxsrc_base>0:emulators/linuxsrc_base \
		linuxsrc-gcc>0:lang/linuxsrc-gcc \
		linuxsrc-make>0:devel/linuxsrc-make

USES=		metaport

.include <bsd.port.mk>
