--- opencbm/include/LINUX/cbm_module.h.orig	2017-09-06 18:59:00.000000000 +0200
+++ opencbm/include/LINUX/cbm_module.h	2018-11-04 18:08:40.031481000 +0100
@@ -20,37 +20,37 @@
 #endif
 #endif
 
+/* all values needed by PARBURST_READ_TRACK and PARBURST_WRITE_TRACK */
+typedef struct PARBURST_RW_VALUE {
+	unsigned char *buffer;
+	int length;
+} PARBURST_RW_VALUE;
+
 #define CBMCTRL_BASE        0xcb
 
-#define CBMCTRL_TALK        _IO(CBMCTRL_BASE, 0)
-#define CBMCTRL_LISTEN      _IO(CBMCTRL_BASE, 1)
+#define CBMCTRL_TALK        _IOW(CBMCTRL_BASE, 0, int)
+#define CBMCTRL_LISTEN      _IOW(CBMCTRL_BASE, 1, int)
 #define CBMCTRL_UNTALK      _IO(CBMCTRL_BASE, 2)
 #define CBMCTRL_UNLISTEN    _IO(CBMCTRL_BASE, 3)
-#define CBMCTRL_OPEN        _IO(CBMCTRL_BASE, 4)
-#define CBMCTRL_CLOSE       _IO(CBMCTRL_BASE, 5)
+#define CBMCTRL_OPEN        _IOW(CBMCTRL_BASE, 4, int)
+#define CBMCTRL_CLOSE       _IOW(CBMCTRL_BASE, 5, int)
 #define CBMCTRL_RESET       _IO(CBMCTRL_BASE, 6)
-#define CBMCTRL_GET_EOI     _IO(CBMCTRL_BASE, 7)
+#define CBMCTRL_GET_EOI     _IOR(CBMCTRL_BASE, 7, int)
 #define CBMCTRL_CLEAR_EOI   _IO(CBMCTRL_BASE, 8)
 
-#define CBMCTRL_PP_READ     _IO(CBMCTRL_BASE, 10)
-#define CBMCTRL_PP_WRITE    _IO(CBMCTRL_BASE, 11)
-#define CBMCTRL_IEC_POLL    _IO(CBMCTRL_BASE, 12)
-#define CBMCTRL_IEC_SET     _IO(CBMCTRL_BASE, 13)
-#define CBMCTRL_IEC_RELEASE _IO(CBMCTRL_BASE, 14)
-#define CBMCTRL_IEC_WAIT    _IO(CBMCTRL_BASE, 15)
-#define CBMCTRL_IEC_SETRELEASE _IO(CBMCTRL_BASE, 16)
+#define CBMCTRL_PP_READ     _IOR(CBMCTRL_BASE, 10, unsigned char)
+#define CBMCTRL_PP_WRITE    _IOW(CBMCTRL_BASE, 11, unsigned char)
+#define CBMCTRL_IEC_POLL    _IOR(CBMCTRL_BASE, 12, int)
+#define CBMCTRL_IEC_SET     _IOW(CBMCTRL_BASE, 13, int)
+#define CBMCTRL_IEC_RELEASE _IOW(CBMCTRL_BASE, 14, int)
+#define CBMCTRL_IEC_WAIT    _IOWR(CBMCTRL_BASE, 15, int)
+#define CBMCTRL_IEC_SETRELEASE _IOW(CBMCTRL_BASE, 16, int)
 
 /* linux constants needed by parallel burst */
-#define CBMCTRL_PARBURST_READ    _IO(CBMCTRL_BASE, 17)
-#define CBMCTRL_PARBURST_WRITE   _IO(CBMCTRL_BASE, 18)
-#define CBMCTRL_PARBURST_READ_TRACK        _IO(CBMCTRL_BASE, 19)
-#define CBMCTRL_PARBURST_WRITE_TRACK _IO(CBMCTRL_BASE, 20)
-#define CBMCTRL_PARBURST_READ_TRACK_VAR    _IO(CBMCTRL_BASE, 21)
-
-/* all values needed by PARBURST_READ_TRACK and PARBURST_WRITE_TRACK */
-typedef struct PARBURST_RW_VALUE {
-	unsigned char *buffer;
-	int length;
-} PARBURST_RW_VALUE;
+#define CBMCTRL_PARBURST_READ    _IOR(CBMCTRL_BASE, 17, unsigned char)
+#define CBMCTRL_PARBURST_WRITE   _IOW(CBMCTRL_BASE, 18, unsigned char)
+#define CBMCTRL_PARBURST_READ_TRACK        _IOW(CBMCTRL_BASE, 19, PARBURST_RW_VALUE)
+#define CBMCTRL_PARBURST_WRITE_TRACK _IOW(CBMCTRL_BASE, 20, PARBURST_RW_VALUE)
+#define CBMCTRL_PARBURST_READ_TRACK_VAR    _IOW(CBMCTRL_BASE, 21, PARBURST_RW_VALUE)
 
 #endif
