PORTNAME=	m4
DISTVERSION=	1.4.19
CATEGORIES=	devel
MASTER_SITES=	GNU

MAINTAINER=	zirias@FreeBSD.org
COMMENT=	GNU M4, Linux version
WWW=		https://www.gnu.org/software/m4/m4.html

LICENSE=	GPLv3
LICENSE_FILE=	${WRKSRC}/COPYING

USES=		cpe linuxsrc:dist,man tar:xz
CPE_VENDOR=	gnu

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
