# Created by: Felix Palmen <felix@palmen-it.de>
# $FreeBSD$

PORTNAME=	xcons
PORTVERSION=	0.2
CATEGORIES=	sysutils

MAINTAINER=	felix@palmen-it.de
COMMENT=	Tool for having an xconsole like display in any terminal

LICENSE=	BSD2CLAUSE

USE_GITHUB=	yes
GH_ACCOUNT=	zirias
GH_TAGNAME=	v${PORTVERSION}

INSTALL_TARGET=	install-strip

.include <bsd.port.mk>
